name: RCSpigotAdapter
version: '${version}'
main: cn.huohuas001.huhobot.RCSpigotAdapter
api-version: '1.16'

commands:
  huhobot:
    description: HuHoBot management commands
    usage: /<command> [status|reconnect|reload|help]
    aliases: [hb, huho]

permissions:
  huhobot.admin:
    description: Allows access to admin commands
    default: op
  huhobot.status:
    description: Allows checking status
    default: true
